---
name: CI

# yamllint disable-line rule:truthy
on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'yarn'
      - uses: scottbrenner/cfn-lint-action@v2
      - run: yarn install --frozen-lockfile
      # Eslint
      - run: yarn lint
      # YAML Lint
      - uses: ibiqlik/action-yamllint@v3
      # Generate Cloudformation
      - run: yarn package --stage ci
      # Cloudformation Lint
      - run: cfn-lint
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: yarn
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: comment, report-markdown
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "junit.xml"
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
